### PR TITLE
Project structure

### PR DESCRIPTION
**Pull request by alishabab**
Hi, Find Live link [here](https://react-online-calc.herokuapp.com/)
## In this milestone, I
- Created react project from create-react-app 
- Added linter and  Github workflow
- Added big.js to project dependency
- Deployed to heroku

### CODE REVIEW

**Comment by fatymahmed** [comment]
Friendly reminder: You should make sure that your repo looks professional before review.
Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
Then apply 3 simple rules from this lesson, make sure that your readme file is descriptive, you can use [this](https://github.com/microverseinc/readme-template) template as a guide
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

**Comment by alishabab** [comment]
I have updated the readme, but in Milestone 1 it was not required.

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required :muscle: 
Hi @alishabab :hand: 
Nice job in this milestone so far :clap: 
But we need to make some changes before moving on.

- [x] We still need to work on your README file. Right now it does not have any relevant information about the Calculator app. We need to update the README file from the bootstrap text generated by `react-create-app` and add one with information about your project. You can use this nice template [here](https://github.com/microverseinc/readme-template), it will give a lot of value to your repository making it looking more professional. Adding a descriptive README file with relevant information it's actually one of the first requirements for milestone 1. These types of requirements (professional repository) are included in the **Microverse general requirements**.
Screenshot from 2020-09-09 09-17-14

And after clicking on the link we have all requirements here:

Screenshot from 2020-09-09 09-17-52

- [x] We also need to add the `prop-types` dependency for type checking props.
Screenshot from 2020-09-09 09-30-39

Please kindly submit for code review again after making these changes.
Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

**Review by shloch — APPROVED** [review]
## hello @Alishabab
Thanks for updates....we got the read me nicely
We're ready for milestone two.....
### Happy coding, you can merge

**Pull request merged**
